version: '3.8'

services:
  db:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    networks:
      - backend
    command: >
      sh -c "apt-get update && apt-get install git -y &&
             git clone https://github.com/RedAzrael/paco-database.git /tmp/db-script &&
             cp /tmp/db-script/* /docker-entrypoint-initdb.d/ &&
             chmod 644 /docker-entrypoint-initdb.d/* &&
             /entrypoint.sh mysqld"


  backend:
    image: python:3.10
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
    networks:
      - backend
      - frontend
    command: >
      sh -c "apt-get update && apt-get install -y git &&
             git clone https://github.com/RedAzrael/paco-backend.git /app &&
             cd /app &&
             pip install -r requirements.txt &&
             python main.py"

  frontend:
    image: node:18
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:3001
    networks:
      - frontend
    ports:
      - "3000:3000"
    command: >
      sh -c "apt-get update && apt-get install -y git &&
             git clone https://github.com/RedAzrael/paco-frontend.git /app &&
             cd /app &&
             npm install &&
             npm start"


networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
